[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/anthropic/*"
  to = "https://api.anthropic.com/:splat"
  status = 200
  force = true
  headers = {X-Api-Key = "env:VITE_ANTHROPIC_KEY", anthropic-version = "2023-06-01"}

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://apis.google.com https://*.firebaseapp.com https://*.googleapis.com https://www.googletagmanager.com; connect-src 'self' https://api.anthropic.com https://*.googleapis.com https://*.firebaseio.com https://*.firebase.com wss://*.firebaseio.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://firestore.googleapis.com https://storage.googleapis.com https://www.google-analytics.com https://analytics.google.com https://region1.google-analytics.com; object-src 'none';"
